#!/bin/bash
# Setup script for adding environment variables to Vercel

echo "🚀 Orderwala Environment Variables Setup"
echo "========================================"
echo ""
echo "This script will help you generate required environment variables"
echo ""

# Generate JWT secrets
echo "Generating JWT secrets..."
JWT_SECRET=$(openssl rand -base64 32)
JWT_REFRESH_SECRET=$(openssl rand -base64 32)
AUTH_SECRET=$(openssl rand -base64 32)

echo "✅ Generated Secrets:"
echo "JWT_SECRET: $JWT_SECRET"
echo "JWT_REFRESH_SECRET: $JWT_REFRESH_SECRET"
echo "AUTH_SECRET: $AUTH_SECRET"
echo ""

# Display instructions
echo "📝 Environment Variables to Add in Vercel Dashboard:"
echo "URL: https://vercel.com/kratechsolutions-6082s-projects/orderwala/settings/environment-variables"
echo ""
echo "========== COPY THESE VALUES =========="
echo ""
echo "Frontend URLs:"
echo "NEXT_PUBLIC_SITE_URL=https://orderwala-kappa.vercel.app"
echo "NEXT_PUBLIC_API_URL=https://api.orderwala.in"
echo ""
echo "Supabase (PostgreSQL):"
echo "NEXT_PUBLIC_SUPABASE_URL=<paste from https://app.supabase.com/project/*/settings/api>"
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=<paste from https://app.supabase.com/project/*/settings/api>"
echo "SUPABASE_SERVICE_ROLE_KEY=<paste from https://app.supabase.com/project/*/settings/api>"
echo ""
echo "Firebase (Real-time):"
echo "NEXT_PUBLIC_FIREBASE_API_KEY=<paste from Firebase config>"
echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=<your-project>.firebaseapp.com"
echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=<your-project-id>"
echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=<bucket>"
echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=<id>"
echo "NEXT_PUBLIC_FIREBASE_APP_ID=<app-id>"
echo ""
echo "Razorpay (Payments):"
echo "NEXT_PUBLIC_RAZORPAY_KEY_ID=<from https://dashboard.razorpay.com/app/keys>"
echo "RAZORPAY_SECRET_KEY=<from https://dashboard.razorpay.com/app/keys>"
echo ""
echo "Authentication:"
echo "JWT_SECRET=$JWT_SECRET"
echo "JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET"
echo "NEXTAUTH_URL=https://orderwala-kappa.vercel.app"
echo "AUTH_SECRET=$AUTH_SECRET"
echo ""
echo "Google OAuth (from https://console.cloud.google.com):"
echo "AUTH_GOOGLE_ID=<your-google-client-id>"
echo "AUTH_GOOGLE_SECRET=<your-google-client-secret>"
echo "GOOGLE_CLIENT_ID=<same as AUTH_GOOGLE_ID>"
echo "GOOGLE_CLIENT_SECRET=<same as AUTH_GOOGLE_SECRET>"
echo ""
echo "Environment:"
echo "NODE_ENV=production"
echo ""
echo "========================================"
echo ""
echo "✅ Steps to complete:"
echo "1. Go to: https://vercel.com/kratechsolutions-6082s-projects/orderwala/settings/environment-variables"
echo "2. For each variable above, click 'Add New'"
echo "3. Paste the values from your services"
echo "4. Select 'Production' environment"
echo "5. Click 'Save'"
echo "6. After adding all variables, run: vercel --prod"
echo ""
echo "🔗 Service URLs:"
echo "- Supabase: https://app.supabase.com"
echo "- Firebase: https://console.firebase.google.com"
echo "- Razorpay: https://dashboard.razorpay.com"
echo "- Google Cloud: https://console.cloud.google.com"
echo ""
