export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type UserRole = 'customer' | 'admin' | 'vendor' | 'delivery';
export type VendorCategory = 'restaurant' | 'grocery' | 'meat' | 'vegetables' | 'general';
export type PaymentMethod = 'cod' | 'online' | 'wallet';
export type PaymentStatus = 'pending' | 'paid' | 'failed' | 'refunded';
export type OrderStatus = 'pending' | 'confirmed' | 'preparing' | 'ready' | 'picked_up' | 'on_the_way' | 'delivered' | 'cancelled';
export type PromoDiscountType = 'percentage' | 'fixed';
export type AddressType = 'home' | 'work' | 'other';

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          name: string;
          email: string | null;
          phone: string | null;
          password_hash: string | null;
          image: string | null;
          role: UserRole;
          is_verified: boolean;
          is_active: boolean;
          wallet_balance: number;
          fcm_token: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email?: string | null;
          phone?: string | null;
          password_hash?: string | null;
          image?: string | null;
          role?: UserRole;
          is_verified?: boolean;
          is_active?: boolean;
          wallet_balance?: number;
          fcm_token?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string | null;
          phone?: string | null;
          password_hash?: string | null;
          image?: string | null;
          role?: UserRole;
          is_verified?: boolean;
          is_active?: boolean;
          wallet_balance?: number;
          fcm_token?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          image: string;
          icon: string | null;
          parent_category_id: string | null;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          image: string;
          icon?: string | null;
          parent_category_id?: string | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          image?: string;
          icon?: string | null;
          parent_category_id?: string | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      vendors: {
        Row: {
          id: string;
          owner_id: string;
          store_name: string;
          slug: string;
          description: string | null;
          logo: string;
          cover_image: string | null;
          phone: string;
          email: string | null;
          address: Json;
          category: VendorCategory;
          cuisines: string[] | null;
          delivery_radius: number;
          min_order_amount: number;
          delivery_fee: number;
          commission_rate: number;
          average_rating: number;
          total_ratings: number;
          total_orders: number;
          is_open: boolean;
          is_verified: boolean;
          is_active: boolean;
          opening_hours: Json;
          bank_details: Json | null;
          documents: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          store_name: string;
          slug: string;
          description?: string | null;
          logo: string;
          cover_image?: string | null;
          phone: string;
          email?: string | null;
          address: Json;
          category: VendorCategory;
          cuisines?: string[] | null;
          delivery_radius?: number;
          min_order_amount?: number;
          delivery_fee?: number;
          commission_rate?: number;
          average_rating?: number;
          total_ratings?: number;
          total_orders?: number;
          is_open?: boolean;
          is_verified?: boolean;
          is_active?: boolean;
          opening_hours?: Json;
          bank_details?: Json | null;
          documents?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          store_name?: string;
          slug?: string;
          description?: string | null;
          logo?: string;
          cover_image?: string | null;
          phone?: string;
          email?: string | null;
          address?: Json;
          category?: VendorCategory;
          cuisines?: string[] | null;
          delivery_radius?: number;
          min_order_amount?: number;
          delivery_fee?: number;
          commission_rate?: number;
          average_rating?: number;
          total_ratings?: number;
          total_orders?: number;
          is_open?: boolean;
          is_verified?: boolean;
          is_active?: boolean;
          opening_hours?: Json;
          bank_details?: Json | null;
          documents?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      products: {
        Row: {
          id: string;
          vendor_id: string;
          category_id: string;
          name: string;
          slug: string;
          description: string | null;
          images: string[];
          price: number;
          discount_price: number | null;
          unit: string;
          stock: number;
          min_order_qty: number;
          max_order_qty: number;
          variants: Json | null;
          tags: string[] | null;
          is_veg: boolean;
          is_featured: boolean;
          is_available: boolean;
          is_active: boolean;
          average_rating: number;
          total_ratings: number;
          total_sold: number;
          preparation_time: number | null;
          nutrition_info: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          vendor_id: string;
          category_id: string;
          name: string;
          slug: string;
          description?: string | null;
          images: string[];
          price: number;
          discount_price?: number | null;
          unit?: string;
          stock?: number;
          min_order_qty?: number;
          max_order_qty?: number;
          variants?: Json | null;
          tags?: string[] | null;
          is_veg?: boolean;
          is_featured?: boolean;
          is_available?: boolean;
          is_active?: boolean;
          average_rating?: number;
          total_ratings?: number;
          total_sold?: number;
          preparation_time?: number | null;
          nutrition_info?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          vendor_id?: string;
          category_id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          images?: string[];
          price?: number;
          discount_price?: number | null;
          unit?: string;
          stock?: number;
          min_order_qty?: number;
          max_order_qty?: number;
          variants?: Json | null;
          tags?: string[] | null;
          is_veg?: boolean;
          is_featured?: boolean;
          is_available?: boolean;
          is_active?: boolean;
          average_rating?: number;
          total_ratings?: number;
          total_sold?: number;
          preparation_time?: number | null;
          nutrition_info?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      orders: {
        Row: {
          id: string;
          order_number: string;
          customer_id: string;
          vendor_id: string;
          delivery_partner_id: string | null;
          items: Json;
          delivery_address: Json;
          subtotal: number;
          delivery_fee: number;
          platform_fee: number;
          discount: number;
          total: number;
          promo_code: string | null;
          payment_method: PaymentMethod;
          payment_status: PaymentStatus;
          razorpay_order_id: string | null;
          razorpay_payment_id: string | null;
          status: OrderStatus;
          status_history: Json;
          scheduled_for: string | null;
          delivery_instructions: string | null;
          cancel_reason: string | null;
          cancelled_by: string | null;
          delivery_partner_location: Json | null;
          estimated_delivery_time: string | null;
          actual_delivery_time: string | null;
          vendor_earnings: number;
          delivery_earnings: number;
          platform_earnings: number;
          rating: number | null;
          review: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_number: string;
          customer_id: string;
          vendor_id: string;
          delivery_partner_id?: string | null;
          items: Json;
          delivery_address: Json;
          subtotal: number;
          delivery_fee?: number;
          platform_fee?: number;
          discount?: number;
          total: number;
          promo_code?: string | null;
          payment_method?: PaymentMethod;
          payment_status?: PaymentStatus;
          razorpay_order_id?: string | null;
          razorpay_payment_id?: string | null;
          status?: OrderStatus;
          status_history?: Json;
          scheduled_for?: string | null;
          delivery_instructions?: string | null;
          cancel_reason?: string | null;
          cancelled_by?: string | null;
          delivery_partner_location?: Json | null;
          estimated_delivery_time?: string | null;
          actual_delivery_time?: string | null;
          vendor_earnings?: number;
          delivery_earnings?: number;
          platform_earnings?: number;
          rating?: number | null;
          review?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          order_number?: string;
          customer_id?: string;
          vendor_id?: string;
          delivery_partner_id?: string | null;
          items?: Json;
          delivery_address?: Json;
          subtotal?: number;
          delivery_fee?: number;
          platform_fee?: number;
          discount?: number;
          total?: number;
          promo_code?: string | null;
          payment_method?: PaymentMethod;
          payment_status?: PaymentStatus;
          razorpay_order_id?: string | null;
          razorpay_payment_id?: string | null;
          status?: OrderStatus;
          status_history?: Json;
          scheduled_for?: string | null;
          delivery_instructions?: string | null;
          cancel_reason?: string | null;
          cancelled_by?: string | null;
          delivery_partner_location?: Json | null;
          estimated_delivery_time?: string | null;
          actual_delivery_time?: string | null;
          vendor_earnings?: number;
          delivery_earnings?: number;
          platform_earnings?: number;
          rating?: number | null;
          review?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      addresses: {
        Row: {
          id: string;
          user_id: string;
          type: AddressType;
          full_name: string;
          phone: string;
          street: string;
          landmark: string | null;
          city: string;
          state: string;
          pincode: string;
          lat: number | null;
          lng: number | null;
          is_default: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type?: AddressType;
          full_name: string;
          phone: string;
          street: string;
          landmark?: string | null;
          city: string;
          state: string;
          pincode: string;
          lat?: number | null;
          lng?: number | null;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: AddressType;
          full_name?: string;
          phone?: string;
          street?: string;
          landmark?: string | null;
          city?: string;
          state?: string;
          pincode?: string;
          lat?: number | null;
          lng?: number | null;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      favorites: {
        Row: {
          id: string;
          user_id: string;
          product_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          product_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          product_id?: string;
          created_at?: string;
        };
      };
      reviews: {
        Row: {
          id: string;
          user_id: string;
          product_id: string | null;
          vendor_id: string | null;
          order_id: string | null;
          rating: number;
          comment: string | null;
          images: string[] | null;
          is_verified: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          product_id?: string | null;
          vendor_id?: string | null;
          order_id?: string | null;
          rating: number;
          comment?: string | null;
          images?: string[] | null;
          is_verified?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          product_id?: string | null;
          vendor_id?: string | null;
          order_id?: string | null;
          rating?: number;
          comment?: string | null;
          images?: string[] | null;
          is_verified?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      promo_codes: {
        Row: {
          id: string;
          code: string;
          description: string;
          discount_type: PromoDiscountType;
          discount_value: number;
          min_order_amount: number;
          max_discount: number | null;
          usage_limit: number;
          used_count: number;
          valid_from: string;
          valid_until: string;
          is_active: boolean;
          applicable_categories: string[] | null;
          applicable_vendors: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          description: string;
          discount_type: PromoDiscountType;
          discount_value: number;
          min_order_amount?: number;
          max_discount?: number | null;
          usage_limit?: number;
          used_count?: number;
          valid_from: string;
          valid_until: string;
          is_active?: boolean;
          applicable_categories?: string[] | null;
          applicable_vendors?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          description?: string;
          discount_type?: PromoDiscountType;
          discount_value?: number;
          min_order_amount?: number;
          max_discount?: number | null;
          usage_limit?: number;
          used_count?: number;
          valid_from?: string;
          valid_until?: string;
          is_active?: boolean;
          applicable_categories?: string[] | null;
          applicable_vendors?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          message: string;
          type: string;
          data: Json | null;
          is_read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          message: string;
          type: string;
          data?: Json | null;
          is_read?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          message?: string;
          type?: string;
          data?: Json | null;
          is_read?: boolean;
          created_at?: string;
        };
      };
      otp_verifications: {
        Row: {
          id: string;
          phone: string;
          otp: string;
          expires_at: string;
          is_verified: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          phone: string;
          otp: string;
          expires_at: string;
          is_verified?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          phone?: string;
          otp?: string;
          expires_at?: string;
          is_verified?: boolean;
          created_at?: string;
        };
      };
      wallet_transactions: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          amount: number;
          balance_after: number;
          description: string;
          reference_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: string;
          amount: number;
          balance_after: number;
          description: string;
          reference_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: string;
          amount?: number;
          balance_after?: number;
          description?: string;
          reference_id?: string | null;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      user_role: UserRole;
      vendor_category: VendorCategory;
      payment_method: PaymentMethod;
      payment_status: PaymentStatus;
      order_status: OrderStatus;
      promo_discount_type: PromoDiscountType;
      address_type: AddressType;
    };
  };
}
